# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build and deploy to Firebase App Tester"
  lane :beta do
    # Ensure that your git status is not dirty
    ensure_git_status_clean

    # Skip version code increment as it's now handled in the CI pipeline

    # Build the Android app (both AAB and APK)
    gradle(
      task: "clean bundleRelease assembleRelease",
      properties: {
        "android.injected.signing.store.file" => ENV["ANDROID_KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["ANDROID_KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["ANDROID_KEY_PASSWORD"],
      }
    )

    # Upload to Firebase App Distribution using Firebase CLI
    sh("firebase appdistribution:distribute app/build/outputs/bundle/release/app-release.aab \
      --app #{ENV["FIREBASE_APP_ID_ANDROID"]} \
      --testers #{ENV["FIREBASE_TESTERS"]} \
      --release-notes \"New beta build\" \
      --token \"#{ENV["FIREBASE_CLI_TOKEN"]}\"")

    # Commit the version bump
    git_commit(
      path: ["app/build.gradle"],
      message: "Bump version code [skip ci]"
    )
  end
end
